---
title: "Getiing and Cleaning Data Course Project"
author: "Junqi Yang"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
The experiments have been carried out with a group of 30 volunteers, who were 19 to 48 years old. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, researchers captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz.

# Variable
## subject &nbsp; &nbsp; &nbsp; &nbsp; 30 <br>
&nbsp; &nbsp; &nbsp; &nbsp; Volunteers taken part in the experiment. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 1...30 .Volunteers identifier

## activity &nbsp; &nbsp; &nbsp; &nbsp; 6 <br>
&nbsp; &nbsp; &nbsp; &nbsp; Activity performed by volunteers in the experiment. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; WALKING <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; WALKING_UPSTAIRS <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; WALKING_DOWNSTAIRS <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; SITTING <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; STANDING <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; LAYING <br>

## timeBodyAccelerometer -mean()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals obody acceleration in X direction captured by subtracting the gravity from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 0.2...0.4 .Floating mean value of time domain signals of body acceleration in X direction

## timeBodyAccelerometer-mean()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Mean value of time domain signals of body acceleration in Y direction captured by subtracting the gravity from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; -0.05...0.001 .Floating mean value of time domain signals of body acceleration in Y direction

## timeBodyAccelerometer-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of body acceleration in Z direction captured by subtracting the gravity from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; -0.16...-0.07 .Floating mean value of time signals of body acceleration in Z direction

## timeBodyAccelerometer-std()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of body acceleration in X direction captured by subtracting the gravity from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.63 .Floating standard deviation of time domain signals of body acceleration in X direction

## timeBodyAccelerometer-std()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of body acceleration in Y direction captured by subtracting the gravity from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.63 .Floating standard deviation of time domain signals of body acceleration in Y direction

## timeBodyAccelerometer-std()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of body acceleration in Z direction captured by subtracting the gravity from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.61 .Floating standard deviation of time domain signals of body acceleration in Z direction

## timeGravityAccelerometer-mean()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of gravity acceleration in X direction captured by subtracting the body acceleration from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.69...1.00 .Floating mean value of time domain signals of gravity acceleration in X direction

## timeGravityAccelerometer-mean()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of gravity acceleration in Y direction captured by subtracting the body acceleration from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.21...0.03 .Floating mean value of time domain signals of gravity acceleration in Y direction

## timeGravityAccelerometer-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of gravity acceleration in Z direction captured by subtracting the body acceleration from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.08...0.18 .Floating mean value of time domain signals of gravity acceleration in Z direction

## timeGravityAccelerometer-std()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of gravity acceleration in X direction captured by subtracting the body acceleration from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -1.00...-0.80 .Floating standard deviation of time domain signals of gravity acceleration in X direction

## timeGravityAccelerometer-std()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of gravity acceleration in Y direction captured by subtracting the body acceleration from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -1.00...-0.64 .Floating standard deviation of time domain signals of gravity acceleration in Y direction

## timeGravityAccelerometer-std()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of gravity acceleration in Z direction captured by subtracting the body acceleration from the total acceleration at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -1.00...-0.60 .Floating standard deviation of time domain signals of gravity acceleration in Z direction

## timeBodyAccelerometerJerk-mean()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signal of body linear acceleration were derived in time to obtain Jerk signals in X direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; 0.04...0.14 .Floating mean value of time domain signal of body linear acceleration were derived in time in X direction

## timeBodyAccelerometerJerk-mean()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of body linear acceleration were derived in time to obtain Jerk signals in Y direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.03...0.06 .Floating mean value of time domain signal of body linear acceleration were derived in time in Y direction

## timeBodyAccelerometerJerk-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of body linear acceleration were derived in time to obtain Jerk signals in Z direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.03...0.06 .Floating mean value of time domain signals of body linear acceleration were derived in time in Z direction

## timeBodyAccelerometerJerk-std()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of body linear acceleration were derived in time to obtain Jerk signals in X direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.55 .Floating standard deviation of time domain signals of body linear acceleration were derived in time in X direction

## timeBodyAccelerometerJerk-std()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of body linear acceleration were derived in time to obtain Jerk signals in Y direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.36 .Floating standard deviation of time domain signals of body linear acceleration were derived in time in Y direction

## timeBodyAccelerometerJerk-std()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of body linear acceleration were derived in time to obtain Jerk signals in Z direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.04 .Floating standard deviation of time domain signals of body linear acceleration were derived in time in Z direction

## timeBodyGyroscope-mean()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time signals of angular velocity vector measured in X direction by the gyroscope for each window sample. The units are radians/second. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.21...0.20 .Floating mean value of time signals of angular velocity vector in X direction

## timeBodyGyroscope-mean()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time signals of angular velocity vector measured in Y direction by the gyroscope for each window sample. The units are radians/second. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.21...0.03 .Floating mean value of time signals of angular velocity vector in Y direction

## timeBodyGyroscope-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time signals of angular velocity vector measured in Z direction by the gyroscope for each window sample. The units are radians/second. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.08...0.18 .Floating mean value of time signals of angular velocity vector in Z direction

## timeBodyGyroscope-std()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviaiton of time signals of angular velocity vector measured in X direction by the gyroscope for each window sample. The units are radians/second. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0.17...0.28 .Floating standard deviation of time signals of angular velocity vector in X direction

## timeBodyGyroscope-std()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviaiton of time signals of angular velocity vector measured in Y direction by the gyroscope for each window sample. The units are radians/second. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.48 .Floating standard deviation of time signals of angular velocity vector in Y direction

## timeBodyGyroscope-std()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviaiton of time signals of angular velocity vector measured in Z direction by the gyroscope for each window sample. The units are radians/second. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.57 .Floating standard deviation of time signals of angular velocity vector in Z direction

## timeBodyGyroscopeJerk-mean()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of angular velicity were derived in time to obtain Jerk signals in X direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.16...0.03 .Floating mean value of time signals of angular velocity vector were derived in time in X direction

## timeBodyGyroscopeJerk-mean()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of angular velicity were derived in time to obtain Jerk signals in Y direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.08...0.14 .Floating mean value of time signals of angular velocity vector were derived in time in Y direction

## timeBodyGyroscopeJerk-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of time domain signals of angular velicity were derived in time to obtain Jerk signals in Z direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...-0.006 .Floating mean value of time signals of angular velocity vector were derived in time in Z direction

## timeBodyGyroscopeJerk-std()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of angular velicity were derived in time to obtain Jerk signals in X direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.18 .Floating standard deviation of time signals of angular velocity vector were derived in time in X direction

## timeBodyGyroscopeJerk-std()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of angular velicity were derived in time to obtain Jerk signals in Y direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.30 .Floating standard deviation of time signals of angular velocity vector were derived in time in Y direction

## timeBodyGyroscopeJerk-std()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of time domain signals of angular velicity were derived in time to obtain Jerk signals in Z direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.20 .Floating standard deviation of time signals of angular velocity vector were derived in time in Z direction

## timeBodyAccelerometerMagnitute-mean() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of magnitude of three-dimensional time domain signals of body acceleration were calculated using the Euclidean norm. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;-0.10...0.09 .Floating mean magnitude of time signals domain of body acceleration

## timeBodyAccelerometerMagnitute-std() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of magnitude of three-dimensional time domain signals of acceleration were calculated using the Euclidean norm. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.10...0.43 .Floating standaar deviation of magnitude of body acceleration in time domain signals

## timeGravityAccelerometerMagnitute-mean() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of magnitude of three-dimensional time domain signals of gravity acceleration were calculated using the Euclidean norm. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.10...0.65 .Floating standar deviation of magnitude of gravity acceleration in time domain signals

## frequencyBodyAccelerometer-mean()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyAccelerometer-mean()-X. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.10...0.54 .Floating mean value of frequency doamin signals of body acceleration in X direction

## frequencyBodyAccelerometer-mean()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyAccelerometer-mean()-Y. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.10...0.54 .Floating mean value of frequency doamin signals of body acceleration in Y direction

## frequencyBodyAccelerometer-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyAccelerometer-mean()-Z. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -0.10...0.29 .Floating mean value of frequency doamin signals of body acceleration in Z direction

## frequencyBodyAccelerometer-std()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyAccelerometer-std()-X. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.66 .Floating standard deviation of frequency doamin signals of body acceleration in X direction

## frequencyBodyAccelerometer-std()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyAccelerometer-std()-Y. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.57 .Floating standard deviation of frequency doamin signals of body acceleration in Y direction

## frequencyBodyAccelerometer-std()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyAccelerometer-std()-Z. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.69 .Floating standard deviation of frequency doamin signals of body acceleration in Z direction

## frequencyBodyAccelerometer-std()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyAccelerometer-std()-Z. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.69 .Floating standard deviation of frequency doamin signals of body acceleration in Z direction

## frequencyBodyAccelerometer-meanFreq()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to obtain a mean frequency(produced by Fast Fourier Transform (FFT)) of body acceleration in X directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.64...0.16 .Floating weighted average of frequency doamin signals of body acceleration in X direction

## frequencyBodyAccelerometer-meanFreq()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to obtain a mean frequency(produced by Fast Fourier Transform (FFT)) of body acceleration in Y directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.38...0.47 .Floating weighted average of frequency doamin signals of body acceleration in Y direction

## frequencyBodyAccelerometer-meanFreq()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to obtain a mean frequency(produced by Fast Fourier Transform (FFT)) of body acceleration in Z directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.52...0.41 .Floating weighted average of frequency doamin signals of body acceleration in Z direction

## frequencyBodyAccelerometerJerk-mean()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals of body acceleration were derived in time to obtain Jerk signals in X direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...-0.50 .Floating mean value of frequency doamin signals of body acceleration were derived in time in X direction

## frequencyBodyAccelerometerJerk-mean()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals of body acceleration were derived in time to obtain Jerk signals in Y direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.28 .Floating mean value of frequency doamin signals of body acceleration were derived in time in Y direction

## frequencyBodyAccelerometerJerk-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals of body acceleration were derived in time to obtain Jerk signals in Z direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.16 .Floating mean value of frequency doamin signals of body acceleration were derived in time in Z direction

## frequencyBodyAccelerometerJerk-std()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of frequency domain signals of body acceleration were derived in time to obtain Jerk signals in X direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.48 .Floating standard deviation of frequency doamin signals of body acceleration were derived in time in X direction

## frequencyBodyAccelerometerJerk-std()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of frequency domain signals of body acceleration were derived in time to obtain Jerk signals in Y direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.35 .Floating standard deviation of frequency doamin signals of body acceleration were derived in time in Y direction

## frequencyBodyAccelerometerJerk-std()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of frequency domain signals of body acceleration were derived in time to obtain Jerk signals in Z direction. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...-0.006 .Floating standard deviation of frequency doamin signals of body acceleration were derived in time in Z direction

## frequencyBodyAccelerometerJerk-meanFreq()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to the time derivative of body acceleration in X directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.50...0.38 .Floating weighted average of frequency doamin signals of body acceleration were derived X direction

## frequencyBodyAccelerometerJerk-meanFreq()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to the time derivative of body acceleration in Y directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.61...0.20 .Floating weighted average of frequency doamin signals of body acceleration were derived Y direction

## frequencyBodyAccelerometerJerk-meanFreq()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to the time derivative of body acceleration in Z directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.63...0.24 .Floating weighted average of frequency doamin signals of body acceleration were derived Z direction

## frequencyBodyGyroscope-mean()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyGyroscope-mean()-X. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -1.00...0.48 .Floating mean value of frequency doamin signals of anular velocity in X direction

## frequencyBodyGyroscope-mean()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyGyroscope-mean()-Y. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -1.00...0.33 .Floating mean value of frequency doamin signals of angular velocity in Y direction

## frequencyBodyGyroscope-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyGyroscope-mean()-Z. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -1.00...0.50 .Floating mean value of frequency doamin signals of angular velocity in Z direction

## frequencyBodyGyroscope-mean()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyGyroscope-mean()-Z. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -1.00...0.50 .Floating mean value of frequency doamin signals of angular velocity in Z direction

## frequencyBodyGyroscope-std()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of frequency domain signals produced by Fast Fourier Transform (FFT) applied to timeBodyGyroscope-mean()-Z. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; -1.00...0.50 .Floating standard deviation of frequency doamin signals of angular velocity in Z direction

## frequencyBodyGyroscope-meanFreq()-X &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to obtain a mean frequency(produced by Fast Fourier Transform (FFT)) of angular velocity in X directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.40...0.25 .Floating weighted average of frequency doamin signals of body acceleration in X direction

## frequencyBodyGyroscope-meanFreq()-Y &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to obtain a mean frequency(produced by Fast Fourier Transform (FFT)) of angular velocity in Y directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.67...0.28 .Floating weighted average of frequency doamin signals of body acceleration in Y direction

## frequencyBodyGyroscope-meanFreq()-Z &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the frequency components to obtain a mean frequency(produced by Fast Fourier Transform (FFT)) of angular velocity in Z directon. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.50...0.38 .Floating weighted average of frequency doamin signals of body acceleration in Z direction

## frequencyBodyAccelerometerMagnitute-mean() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of magnitude of three-dimensional frequnce domain signals of body acceleration were calculated using the Euclidean norm.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.59 .Floating mean value of magnitude of frequency domain signals of body acceleration

## frequencyBodyAccelerometerMagnitute-std() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of magnitude of three-dimensional frequnce domain signals of body acceleration were calculated using the Euclidean norm.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.18 .Floating standard deviation of magnitude of frequency domain signals of body acceleration

## frequencyBodyAccelerometerMagnitute-meanFreq() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the magnitude of three-dimensional frequnce domain signals of body acceleration were calculated using the Euclidean norm. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.32...0.44 .Floating weighted average of the magnitude of three-dimensional frequency doamin signals of body acceleration

## frequencyBodyAccelerometerJerkMagnitute-mean() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of the magnitude of three-dimensional frequnce domain signals of body acceleration were derived in time. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.54 .Floating mean time derivative of the magnitude of three-dimensional frequency doamin signals of body acceleration

## frequencyBodyAccelerometerJerkMagnitute-std() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of the magnitude of three-dimensional frequnce domain signals of body acceleration were derived in time. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.32 .Floating standard devitaion of time derivative of the magnitude of three-dimensional frequency doamin signals of body acceleration

## frequencyBodyAccelerometerJerkMagnitute-meanFreq() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the magnitude of three-dimensional frequnce domain signals of body acceleration were derived in time. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.13...0.49 .Floating weighted average of time derivative of the magnitude of three-dimensional frequency doamin signals of body acceleration

## frequencyBodyGyroscopeMagnitute-mean() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of the magnitude of three-dimensional frequnce domain signals of angular velocity. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.99...0.21 .Floating mean value of the magnitude of three-dimensional frequency doamin signals of angular velocity

## frequencyBodyGyroscopeMagnitute-std() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of the magnitude of three-dimensional frequnce domain signals of angular velocity. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.99...0.24 .Floating standard deviation of the magnitude of three-dimensional frequency doamin signals of angular velocity

## frequencyBodyGyroscopeMagnitute-meanFreq() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weighted average of the magnitude of three-dimensional frequnce domain signals of angular velocity. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.46...0.41 .Floating weighted average of the magnitude of three-dimensional frequency doamin signals of angular velocity

## frequencyBodyGyroscopeJerkMagnitute-mean() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mean value of the magnitude of three-dimensional frequnce domain signals of angular velocity were derived in time. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.15 .Floating mean time derivative of the magnitude of three-dimensional frequency doamin signals of angular velocity

## frequencyBodyGyroscopeJerkMagnitute-std() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of the magnitude of three-dimensional frequnce domain signals of angular velocity were derived in time. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.15 .Floating standard deviation of time derivative of the magnitude of three-dimensional frequency doamin signals of angular velocity

## frequencyBodyGyroscopeJerkMagnitute-std() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Standard deviation of the magnitude of three-dimensional frequnce domain signals of angular velocity were derived in time. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.15 .Floating standard deviation of time derivative of the magnitude of three-dimensional frequency doamin signals of angular velocity

## frequencyBodyGyroscopeJerkMagnitute-meanFreq() &nbsp; &nbsp; &nbsp; &nbsp; 180 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Weignted average of the magnitude of three-dimensional frequnce domain signals of angular velocity were derived in time. <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -1.00...0.19 .Floating weighted average of time derivative of the magnitude of three-dimensional frequency
